Vagrant.configure("2") do |config|
    config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
      
    config.vm.define :master do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "master"
      master.vm.network :private_network, ip: "192.168.56.100"
      master.vm.network "public_network"
          
    end
  
    %w{worker1 worker2}.each_with_index do |name, i|
      config.vm.define name do |worker|
        worker.vm.box = "ubuntu/focal64"
        worker.vm.hostname = name
        worker.vm.network :private_network, ip: "192.168.56.#{i + 100}"
        worker.vm.network "public_network"
       end
    end
  
  
  end
  
