apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
      <head>
        <title>Static Page</title>
      </head>
      <body>
        <h1>Static Page</h1>
      </body>
    </html>
